[package]
name = "ril"
authors = ["jay3332"]
version = "0.1.0"
license = "MIT"
edition = "2021"
description = "Rust Imaging Library: A high-level image processing crate for Rust"
repository = "https://github.com/jay3332/ril"
homepage = "https://github.com/jay3332/ril"
readme = "README.md"
keywords = ["ril", "imaging", "image", "processing", "editing", "graphics"]
categories = ["encoding", "graphics", "multimedia", "visualization"]

[dependencies]
miniz_oxide = "^0.5"
