name: Benchmark

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install latest stable Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Setup cache
      uses: Swatinem/rust-cache@v1
    
    - name: Install gnuplot
      run: sudo apt install gnuplot

    - name: Install tools
      run: cargo install cargo-criterion criterion-table

    - name: Run benchmark
      run: cargo criterion --message-format=json | criterion-table > BENCHMARKS.md
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: BENCHMARKS.md
        path: BENCHMARKS.md
    
    - name: Add output markdown to job summary
      run: cat BENCHMARKS.md >> $GITHUB_STEP_SUMMARY
