name: Documentations

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install latest stable Rust toolchain with clippy
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy

    - name: Setup cache
      uses: Swatinem/rust-cache@v1

    - run: cargo doc --all-features --workspace --no-deps
    - run: echo "<meta http-equiv=\"refresh\" content=\"0; url=ril\">" > target/doc/index.html
    - run: cp -r target/doc ./docs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ril-docs
        path: ./docs
